### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by paq** [plusone-masaki/csv-plus#15]
Could you please clarify the license? E.g., MIT license.

**Comment by tomoya** [comment]
Hi, @plusone-masaki 
https://twitter.com/ykzts/status/1406939355042570244

AFAIK, The handsontable can only be used as OSS up to v6.2.2.
For now, this product has a license issue.
You need to downgrade the library version if you publish it as free software.
Thank you,

**Comment by plusone-masaki** [comment]
Thank you for contacting us.
We are currently working on this issue and will be releasing a license-safe version using v6.2.2 today.

**Comment by plusone-masaki** [comment]
I have just released a license-safe version of v0.7.7 with HandsOnTable @ 6.2.2.
I think this solved the licensing problem.
I'll list the license on the documentation page, so I'd like to close this issue afterwards.

**Comment by tomoya** [comment]
I respect your quick work. It sure is nice to have solved the Handsontable license issue.
But, this issue has not yet been resolved, so it is too early to close this.

To resolve this issue, you must put the license file in this repository.
Because the license field in `package.json` has no meaning as a license.

Please, let you add the MIT license file If you choose an MIT license for this repository.
https://docs.github.com/ja/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by plusone-masaki** [comment]
Added LICENSE file.
